### ISSUE TITLE
Failing to push: `unsupported MIME type for compression: application/vnd.in-toto+json`

### ISSUE THREAD

**Issue by m-roberts** [devcontainers/ci#241] opened 2023-04-22 08:01 UTC
Logs:

```
2023-04-22T07:35:36.8375351Z Copying multiplatform image '************.dkr.ecr.eu-west-1.amazonaws.com/************/service:refname'...
2023-04-22T07:35:36.8380198Z ##[group]📌 Copying image...
2023-04-22T07:35:36.8450595Z [command]/usr/bin/skopeo copy --all oci-archive:/tmp/output.tar:refname docker://************.dkr.ecr.eu-west-1.amazonaws.com/************/service:refname
2023-04-22T07:35:40.0195907Z Getting image list signatures
2023-04-22T07:35:40.0199664Z Copying 4 of 4 images in list
2023-04-22T07:35:40.0202360Z Copying image sha256:ff28f6f4ba78e4485c40f9efb99532022a30079ebfdcbcd0e34edc9caa1a136a (1/4)
2023-04-22T07:35:40.0202792Z Getting image source signatures
2023-04-22T07:35:41.5762085Z Copying blob sha256:26c5c85e47da3022f1bdb9a112103646c5c29517d757e95426f16e4bd9533405
2023-04-22T07:35:46.8990190Z Copying blob sha256:9e79879be9c7cd8edaba21c88fa4be66ea65e7a3f56f98e7820bcb7dedac3b00
2023-04-22T07:35:50.4884598Z Copying blob sha256:5dd57ff8d4118e3a008cef44993c75ef683711925dc9866290a8064ce5a9e86b
2023-04-22T07:35:54.9993415Z Copying blob sha256:50349b1ecdebde63cb306d20e04683503f2e038ce6109bb5ba28e6031dc2bcbd
2023-04-22T07:35:57.7426722Z Copying blob sha256:431f8d1d6c10e17de87aef2faab02ee80561cbecbbf341c61932173d6001e562
2023-04-22T07:36:01.4758296Z Copying blob sha256:3f50bb9508ea6af9f689aff4784d88efa9a2c9e1cccd40aea3a489b6351baf37
2023-04-22T07:36:04.2780723Z Copying blob sha256:d46a9029dd41df27999b9e1e31cb9c6ecbdfc02ba37040efbe509faa60346234
2023-04-22T07:36:07.0770672Z Copying blob sha256:9ad95ebf3e484e9ebe12df20071b7073192dc82215706e2812affdfd613b7069
2023-04-22T07:36:15.1182914Z Copying blob sha256:60b5a1dc05d5b176370dfb46bcf78eae5ffe1d6335dd769a4ff042f42a8ce01b
2023-04-22T07:36:22.6271505Z Copying blob sha256:fb4ade4bf29a94db211e2239b91cae85aa30557feb2f37416fcf438a72367a40
2023-04-22T07:36:31.4173974Z Copying blob sha256:9f964e393f77c1604856520268585c6e7f7d4de6b32ddfcfd89a603941c415bf
2023-04-22T07:36:34.2992133Z Copying blob sha256:73d948287219b1a2cd88f6011e68010ac30b3aefa9d2a1e7a4a214d0d10e8b17
2023-04-22T07:36:37.1286632Z Copying blob sha256:0dcde95fcfbea228fb774160acac90e59b0b3c600bc30a9650b76bfa0200641c
2023-04-22T07:36:40.0029384Z Copying blob sha256:d0920fd2c56e877b97bfe4f9b8c88ed18a61e352e397197668e3e9d155665778
2023-04-22T07:36:49.9225763Z Copying config sha256:ea9f4cbfdc713f6e91547d0ca8fabaa40faa114af99334869a6ac17ce1e2bd5b
2023-04-22T07:36:52.2610300Z Writing manifest to image destination
2023-04-22T07:36:52.9406211Z Storing signatures
2023-04-22T07:36:52.9410066Z Copying image sha256:20ebef483a645cdbb025f0aaa40574dafb9e62f6af440b8a5719d404300588c8 (2/4)
2023-04-22T07:36:52.9413340Z Getting image source signatures
2023-04-22T07:36:53.4472670Z Copying blob sha256:ebc3dc5a2d72427c585c8cda7574a75d96e04b9a37572bd3af0bff905abefbb9
2023-04-22T07:36:58.5637394Z Copying blob sha256:03005f146bfbd122db775ced24c8705cc225204acf92dc68c2e9f2d57a6b9883
2023-04-22T07:37:02.2404270Z Copying blob sha256:4a6241eb8776a2513eecafb4d2ab028f65a1090f10f42794a181e2e2b365d366
2023-04-22T07:37:06.9361391Z Copying blob sha256:dc63d781071357ddf94fc707d3a14a5a615462544079b262aafbb727e46a008a
2023-04-22T07:37:09.7715527Z Copying blob sha256:510f1ec7a0b2a74245b1c7290a3f99066da2ad9d3cdd2b8496d8b18bcd43c516
2023-04-22T07:37:13.5059681Z Copying blob sha256:52c2c1a4b2bc4dc7779191fac402c221d4227d27f1f4dca4bdca2afc336624c0
2023-04-22T07:37:16.2506737Z Copying blob sha256:d46a9029dd41df27999b9e1e31cb9c6ecbdfc02ba37040efbe509faa60346234
2023-04-22T07:37:16.7583777Z Copying blob sha256:89e53e6aceb31559cb21732b2afb5323a27e0c2552a4ef8b3d487c6663ab06a0
2023-04-22T07:37:24.5794473Z Copying blob sha256:28149d4e07def64c1a16460732586bbf0befeb3c15bc4f552968783c30c5fd5e
2023-04-22T07:37:31.1390568Z Copying blob sha256:cd177c6b5fb0cd24f4c75c2255e1fb23e3037af836718f9cb4676c2068e98ee2
2023-04-22T07:37:39.4446366Z Copying blob sha256:1bb0320bb8cc30b10da18323f0d221accb428b09ebdea9387842d8f3cdbecad2
2023-04-22T07:37:42.4082890Z Copying blob sha256:3a2802e9e521ae3690a61c2ffaeb462b244213f0d978ee728f3040bd4d661e0c
2023-04-22T07:37:45.1948105Z Copying blob sha256:ccf3b083ae135b57cc6d27f1e658cdfb001ded4bee6aaa4c33a091dc333782c3
2023-04-22T07:37:47.9785936Z Copying blob sha256:7cc32ab452f82d077433335b20f848a5a72e4740ce1df143172281c631db8390
2023-04-22T07:37:57.1330777Z Copying config sha256:a83ce61ef432021a7fc2fde570e63030d055371d1013adc6463486460d37f56c
2023-04-22T07:37:59.5956828Z Writing manifest to image destination
2023-04-22T07:38:00.2830818Z Storing signatures
2023-04-22T07:38:00.2833447Z Copying image sha256:877a76c89426534f016613b4288910d6c80525f4ce0936937857c975abf0d781 (3/4)
2023-04-22T07:38:00.2837865Z Getting image source signatures
2023-04-22T07:38:00.7875639Z Copying blob sha256:1185eb2e9da29d82e16fb024c87d81585ef30ab8085eb8e744091a046b5c372a
2023-04-22T07:38:02.6885816Z time="2023-04-22T07:38:02Z" level=fatal msg="creating an updated image manifest: preparing updated manifest, layer \"sha256:6b6bec478ee570a3e1b3f963f3078a6819e4d49667b06eb9f3727cb5ece103ad\": unsupported MIME type for compression: application/vnd.in-toto+json"
2023-04-22T07:38:02.7008774Z ##[error]Error: skopeo copy failed with 1
2023-04-22T07:38:02.7044821Z ##[endgroup]
```

**Comment by bamurtaugh** [comment] 2023-04-25 21:53
Thanks for opening @m-roberts. Could you provide some details on when you're encountering this?

**Comment by stuartleeks** [comment] 2023-04-26 13:11
This sounds like a possible duplicate of #191. @m-roberts - can you try installing a later version of skopeo as per  https://github.com/devcontainers/ci/issues/191#issuecomment-1416384710

**Comment by stuartleeks** [comment] 2023-05-02 17:16
Great - thanks for letting us know. I'll close this issue as we have others tracking catching the condition and outputting suggestions

**Closed by stuartleeks** 2023-05-02 17:16 UTC
